# Generated by Django 5.1.4 on 2024-12-24 00:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DocumentEditor",
            new_name="DocumentCollaborator",
        ),
        migrations.RemoveField(
            model_name="document",
            name="editor",
        ),
        migrations.AddField(
            model_name="document",
            name="collaborator",
            field=models.ManyToManyField(
                related_name="collaborator",
                through="editor.DocumentCollaborator",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
