# Generated by Django 5.1.4 on 2024-12-24 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("editor", "0002_rename_documenteditor_documentcollaborator_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="content",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
